### ISSUE TITLE
生成的目录有的无法在 git 上正常跳转

### ISSUE THREAD

**Issue by Darian1996** [houbb/markdown-toc#6]
![image](https://user-images.githubusercontent.com/37619525/61347931-59b0e400-a891-11e9-9df0-d6ce297d5c03.png)

https://github.com/Darian1996/my-tools/blob/master/README.md#posix-thread-%E5%90%8C%E6%AD%A5-api

看下这个文件的这三个无法正常跳转，是不是有什么限定？？？

谢谢

**Comment by Darian1996** [comment]
中文的 `：` 结尾的我去掉 `:` 就可以跳转了
https://github.com/Darian1996/my-tools/blob/master/README.md#posix-thread-%E4%BB%8B%E7%BB%8D


中文的 `（）` 去掉，可以正常跳转

https://github.com/Darian1996/my-tools/blob/master/README.md#%E4%B8%89%E5%A4%A7%E5%8E%9F%E8%AF%ADprimitives

请问下这类似的情况可以解决吗？


![image](https://user-images.githubusercontent.com/37619525/61348391-0475d200-a893-11e9-960c-e0eb62a584d9.png)


我通过点击 锚点  拿到的 链接。这个可不可以解决？

**Comment by houbb** [comment]
应该是中文的一些符号被 github 移除了，本周有时间调整下即可。

**Comment by houbb** [comment]
> 中文的 `：` 结尾的我去掉 `:` 就可以跳转了
> https://github.com/Darian1996/my-tools/blob/master/README.md#posix-thread-%E4%BB%8B%E7%BB%8D
> 
> 中文的 `（）` 去掉，可以正常跳转
> 
> https://github.com/Darian1996/my-tools/blob/master/README.md#%E4%B8%89%E5%A4%A7%E5%8E%9F%E8%AF%ADprimitives
> 
> 请问下这类似的情况可以解决吗？
> 
> ![image](https://user-images.githubusercontent.com/37619525/61348391-0475d200-a893-11e9-960c-e0eb62a584d9.png)
> 
> 我通过点击 锚点 拿到的 链接。这个可不可以解决？
.
v1.0.8 版本已修复此BUG，已经发布到中央仓库。
